OpenShift user: chiefkeeft@gmail.com  
OpenShift password: 7ePMc34L  
OpenShift application name: |myapp123|
OpenShift domain: starter-us-west-2.openshift.com
Deploy only from <chiefkeeft>/myapp? |yes| 
Encrypt password? |yes| 
