language: php
php:
- '5.4'
- '5.5'
- '5.6'
- '7.0'
- '7.1'
- hhvm
- nightly
deploy:
  provider: openshift
  user: chiefkeeft@gmail.com
  password: 7ePMc34L
  app: wordpress
  domain: starter-us-west-2.openshift.com
  on:
    repo: chiefkeeft/wordpress-ci
